version: "3.4"
services:
    rnode_150_r1:
        build: ./rnode_150_r1
        image: 127.0.0.1:5000/rnode_150_r1
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.default.rp_filter=0
            - net.ipv4.conf.all.rp_filter=0
        privileged: true
        networks:
            net_150_net0:
                ipv4_address: 10.150.0.254
            net_ix_ix100:
                ipv4_address: 10.100.0.150

        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "150"
            org.seedsecuritylabs.seedemu.meta.nodename: "r1"
            org.seedsecuritylabs.seedemu.meta.role: "Router"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.150.0.254/24"
            org.seedsecuritylabs.seedemu.meta.net.1.name: "ix100"
            org.seedsecuritylabs.seedemu.meta.net.1.address: "10.100.0.150/24"

    rnode_150_r2:
        build: ./rnode_150_r2
        image: 127.0.0.1:5000/rnode_150_r2
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.default.rp_filter=0
            - net.ipv4.conf.all.rp_filter=0
        privileged: true
        networks:
            net_150_net0:
                ipv4_address: 10.150.0.253
            net_150_net1:
                ipv4_address: 10.150.1.254

        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "150"
            org.seedsecuritylabs.seedemu.meta.nodename: "r2"
            org.seedsecuritylabs.seedemu.meta.role: "Router"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.150.0.253/24"
            org.seedsecuritylabs.seedemu.meta.net.1.name: "net1"
            org.seedsecuritylabs.seedemu.meta.net.1.address: "10.150.1.254/24"

    rnode_150_r3:
        build: ./rnode_150_r3
        image: 127.0.0.1:5000/rnode_150_r3
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.default.rp_filter=0
            - net.ipv4.conf.all.rp_filter=0
        privileged: true
        networks:
            net_150_net1:
                ipv4_address: 10.150.1.253
            net_150_net2:
                ipv4_address: 10.150.2.254

        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "150"
            org.seedsecuritylabs.seedemu.meta.nodename: "r3"
            org.seedsecuritylabs.seedemu.meta.role: "Router"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.150.1.253/24"
            org.seedsecuritylabs.seedemu.meta.net.1.name: "net2"
            org.seedsecuritylabs.seedemu.meta.net.1.address: "10.150.2.254/24"

    rnode_150_r4:
        build: ./rnode_150_r4
        image: 127.0.0.1:5000/rnode_150_r4
        cap_add:
            - ALL
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.default.rp_filter=0
            - net.ipv4.conf.all.rp_filter=0
        privileged: true
        networks:
            net_150_net2:
                ipv4_address: 10.150.2.253
            net_ix_ix101:
                ipv4_address: 10.101.0.150

        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "150"
            org.seedsecuritylabs.seedemu.meta.nodename: "r4"
            org.seedsecuritylabs.seedemu.meta.role: "Router"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net2"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.150.2.253/24"
            org.seedsecuritylabs.seedemu.meta.net.1.name: "ix101"
            org.seedsecuritylabs.seedemu.meta.net.1.address: "10.101.0.150/24"


networks:
    net_150_net0:
        driver_opts:
            com.docker.network.driver.mtu: 1500
        ipam:
            config:
                - subnet: 10.150.0.0/24
        labels:
            org.seedsecuritylabs.seedemu.meta.type: "local"
            org.seedsecuritylabs.seedemu.meta.scope: "150"
            org.seedsecuritylabs.seedemu.meta.name: "net0"
            org.seedsecuritylabs.seedemu.meta.prefix: "10.150.0.0/24"

    net_150_net1:
        driver_opts:
            com.docker.network.driver.mtu: 1500
        ipam:
            config:
                - subnet: 10.150.1.0/24
        labels:
            org.seedsecuritylabs.seedemu.meta.type: "local"
            org.seedsecuritylabs.seedemu.meta.scope: "150"
            org.seedsecuritylabs.seedemu.meta.name: "net1"
            org.seedsecuritylabs.seedemu.meta.prefix: "10.150.1.0/24"

    net_150_net2:
        driver_opts:
            com.docker.network.driver.mtu: 1500
        ipam:
            config:
                - subnet: 10.150.2.0/24
        labels:
            org.seedsecuritylabs.seedemu.meta.type: "local"
            org.seedsecuritylabs.seedemu.meta.scope: "150"
            org.seedsecuritylabs.seedemu.meta.name: "net2"
            org.seedsecuritylabs.seedemu.meta.prefix: "10.150.2.0/24"

    net_ix_ix100:
        external:
            name: sim_ix_net_ix_ix100
        driver: overlay
        labels:
            org.seedsecuritylabs.seedemu.meta.type: "global"
            org.seedsecuritylabs.seedemu.meta.scope: "ix"
            org.seedsecuritylabs.seedemu.meta.name: "ix100"
            org.seedsecuritylabs.seedemu.meta.prefix: "10.100.0.0/24"

    net_ix_ix101:
        external:
            name: sim_ix_net_ix_ix101
        driver: overlay
        labels:
            org.seedsecuritylabs.seedemu.meta.type: "global"
            org.seedsecuritylabs.seedemu.meta.scope: "ix"
            org.seedsecuritylabs.seedemu.meta.name: "ix101"
            org.seedsecuritylabs.seedemu.meta.prefix: "10.101.0.0/24"



